### ISSUE TITLE
Invalid type url found

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-tools#44]
This code
```
  public static Extension mosaicism(double percentage) {
      String percentageString = String.format("%.1f%%", percentage);
      ByteString bstring =  ByteString.copyFromUtf8(percentageString);
      Any perc = Any.newBuilder().setValue(bstring).build();
      return Extension.newBuilder().setName("mosaicism").addValue(perc).build();
  }
```
compiles but when we try to serialize it, we get an error "Invalid type url found" with no additional information.  Looking at the API documentation here https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Any
the reason appears to be that we cannot use Any with text, we would need to supply native (binary) protobuf as well as a URL that describes the scheme. I am not sure that this is what we intended, and wonder if we can change the datatype of value to string? @julesjacobsen @ahwagner

**Comment by julesjacobsen** [comment]
The 'Any' class is not a great way of adding this data. It's a wrapped for a strongly typed proto object where the sender and receiver both have access to the schema describing the wrapped object. 

Thanks to some [extremely](https://codeburst.io/protocol-buffers-part-2-the-untold-parts-of-using-any-6a328560048d) [helpful](https://codeburst.io/protocol-buffers-part-3-json-format-e1ca0af27774) [blogs](https://blog.envoyproxy.io/dynamic-extensibility-and-protocol-buffers-dcd0bf0b8801) a solution to this can be done like so:

```java 
package org.phenopackets.phenopackettools.builder.builders;

import com.google.protobuf.Any;
import com.google.protobuf.StringValue;
import org.ga4gh.vrsatile.v1.Extension;


public class Extensions {

  public static Extension mosaicism(double percentage) {
      String percentageString = String.format("%.1f%%", percentage);
      Any perc = Any.pack(StringValue.of(percentageString));
      return Extension.newBuilder().setName("mosaicism").addValue(perc).build();
  }
}
```

and in the writer:

```java
public class ExamplesCommand implements Callable<Integer> {

   private final JsonFormat.TypeRegistry typeRegistry = JsonFormat.TypeRegistry.newBuilder()
            .add(StringValue.getDescriptor())
            .build();

    private final JsonFormat.Printer jsonPrinter = JsonFormat.printer()
            .usingTypeRegistry(typeRegistry);

// lots and lots of omitted code
            String json = jsonPrinter.print(message);
}
```

which leads to this output:

```yaml
      - subjectOrBiosampleId: "biosample.1"
        interpretationStatus: "CAUSATIVE"
        variantInterpretation:
          acmgPathogenicityClassification: "PATHOGENIC"
          therapeuticActionability: "ACTIONABLE"
          variationDescriptor:
            variation:
              copyNumber:
                Id: "ga4gh:VCN.AFfJws1M4Lg8w1O3XknmHYc9TU2hHYpp"
                allele:
                  sequenceLocation:
                    sequenceId: "refseq:NC_000013.14"
                    sequenceInterval:
                      startNumber:
                        value: "26555377"
                      endNumber:
                        value: "62280955"
                number:
                  value: "1"
            extensions:
            - name: "mosaicism"
              value:
              - '@type': "type.googleapis.com/google.protobuf.StringValue"
                value: "40.0%"
```

So it 'works' but is not ideal. In the prior `variationDescriptor` you used an `expression`:

```yaml
expressions:
            - syntax: "allele-frequency"
              value: "25.0%"
```

So perhaps that's the way to go in this case too? Ideally though, VRSATILE or VRS would have a mechanism of expressing mosaicism.
